
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jvhdetgbiuyxdqxeenwp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp2aGRldGdiaXV5eGRxeGVlbndwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NDE4MTgsImV4cCI6MjA2MTQxNzgxOH0.K9RGcBpRHKqx22dChLm-6faKVxAGoO2Q36RykbJCIMU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
